# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tableplus = {
    pname = "tableplus";
    version = "0.1.284";
    src = fetchurl {
      url = "https://deb.tableplus.com/debian/24/pool/main/t/tableplus/tableplus_0.1.284_amd64.deb";
      sha256 = "sha256-wQm0uCGtj5aqAeNH8bI2EsH4MRDOhZyuB04n++rnaQY=";
    };
  };
}
